// <auto-generated />
namespace LocalsScout.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NM_relacija_users_lokali : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NM_relacija_users_lokali));
        
        string IMigrationMetadata.Id
        {
            get { return "202012191431223_N-M_relacija_users_lokali"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
