// <auto-generated />
namespace LocalsScout.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Category_za_Lokal1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Category_za_Lokal1));
        
        string IMigrationMetadata.Id
        {
            get { return "202012191528550_Category_za_Lokal1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
